app:
    resource: '@AppBundle/Controller/'
    type: annotation
articles:
    type: rest
    resource: AppBundle\Controller\ArticleController
articles_post:
    path: /articles
    methods: [POST]
    defaults:
       _controller: AppBundle\Controller\ArticleController:postArticlesAction
       _format: json
